//! A meson build directory read as a corpus: every compile in its `compile_commands.json`, with
//! the flags that build used.
//!
//! The other sources are code and a unit says how to compile it. A project the size of Postgres
//! does not fit that shape. Its translation units are compiled with a dozen different sets of
//! include paths and defines, some of them are generated by the build, and several are compiled
//! more than once for different libraries. Writing that down in a manifest would be writing a
//! second build system that goes stale with every release, when the first one already records
//! every compile it makes. So the build directory is the corpus, and the compile database in it
//! is the list of cases.
//!
//! The database is JSON, and the harness has no dependencies, so the reader for it is here. It
//! reads the whole of JSON rather than the part meson writes today, because the part meson writes
//! is not a promise.

use std::collections::HashMap;
use std::fs;
use std::path::{Component, Path, PathBuf};

use crate::corpus::Unit;
use crate::differ::{Case, Found};
use crate::toml::Error;

/// The compile database's name inside a build directory.
pub const DATABASE: &str = "compile_commands.json";

/// One JSON value.
#[derive(Debug, Clone, PartialEq)]
pub enum Value {
    /// `null`.
    Null,
    /// `true` or `false`.
    Bool(bool),
    /// A number, kept as it was written since nothing here does arithmetic on one.
    Number(String),
    /// A string, with its escapes undone.
    Str(String),
    /// An array.
    Array(Vec<Value>),
    /// An object, in the order its members were written.
    Object(Vec<(String, Value)>),
}

impl Value {
    /// The member of an object with that key.
    #[must_use]
    pub fn get(&self, key: &str) -> Option<&Value> {
        match self {
            Value::Object(members) => members.iter().find(|(k, _)| k == key).map(|(_, v)| v),
            _ => None,
        }
    }

    /// The string this is, if it is one.
    #[must_use]
    pub fn as_str(&self) -> Option<&str> {
        match self {
            Value::Str(s) => Some(s),
            _ => None,
        }
    }
}

/// Reads one JSON document.
///
/// # Errors
///
/// When the text is not JSON, with the byte offset where it stopped being JSON.
pub fn parse(text: &str) -> Result<Value, String> {
    let mut reader = Reader { bytes: text.as_bytes(), at: 0 };
    let value = reader.value(0)?;
    reader.space();
    if reader.at != reader.bytes.len() {
        return Err(reader.fail("more text after the value"));
    }
    Ok(value)
}

/// How deep arrays and objects may nest before the reader gives up, so that a hostile file is
/// an error rather than a stack overflow.
const DEPTH: usize = 256;

struct Reader<'a> {
    bytes: &'a [u8],
    at: usize,
}

impl Reader<'_> {
    fn fail(&self, what: &str) -> String {
        format!("{what} at byte {}", self.at)
    }

    fn space(&mut self) {
        while self.at < self.bytes.len()
            && matches!(self.bytes[self.at], b' ' | b'\t' | b'\n' | b'\r')
        {
            self.at += 1;
        }
    }

    fn peek(&self) -> Option<u8> {
        self.bytes.get(self.at).copied()
    }

    fn word(&mut self, word: &str, value: Value) -> Result<Value, String> {
        if self.bytes[self.at..].starts_with(word.as_bytes()) {
            self.at += word.len();
            Ok(value)
        } else {
            Err(self.fail("a word that is not true, false or null"))
        }
    }

    fn value(&mut self, depth: usize) -> Result<Value, String> {
        if depth > DEPTH {
            return Err(self.fail("nested too deep"));
        }
        self.space();
        match self.peek() {
            None => Err(self.fail("the text ended where a value should be")),
            Some(b'n') => self.word("null", Value::Null),
            Some(b't') => self.word("true", Value::Bool(true)),
            Some(b'f') => self.word("false", Value::Bool(false)),
            Some(b'"') => self.string().map(Value::Str),
            Some(b'[') => {
                self.at += 1;
                let mut items = Vec::new();
                self.space();
                if self.peek() == Some(b']') {
                    self.at += 1;
                    return Ok(Value::Array(items));
                }
                loop {
                    items.push(self.value(depth + 1)?);
                    self.space();
                    match self.peek() {
                        Some(b',') => self.at += 1,
                        Some(b']') => {
                            self.at += 1;
                            return Ok(Value::Array(items));
                        }
                        _ => return Err(self.fail("an array that does not go on with , or ]")),
                    }
                }
            }
            Some(b'{') => {
                self.at += 1;
                let mut members = Vec::new();
                self.space();
                if self.peek() == Some(b'}') {
                    self.at += 1;
                    return Ok(Value::Object(members));
                }
                loop {
                    self.space();
                    if self.peek() != Some(b'"') {
                        return Err(self.fail("an object key that is not a string"));
                    }
                    let key = self.string()?;
                    self.space();
                    if self.peek() != Some(b':') {
                        return Err(self.fail("an object key with no : after it"));
                    }
                    self.at += 1;
                    let value = self.value(depth + 1)?;
                    members.push((key, value));
                    self.space();
                    match self.peek() {
                        Some(b',') => self.at += 1,
                        Some(b'}') => {
                            self.at += 1;
                            return Ok(Value::Object(members));
                        }
                        _ => return Err(self.fail("an object that does not go on with , or }")),
                    }
                }
            }
            Some(b'-' | b'0'..=b'9') => {
                let start = self.at;
                while self.peek().is_some_and(|b| {
                    b.is_ascii_digit() || matches!(b, b'-' | b'+' | b'.' | b'e' | b'E')
                }) {
                    self.at += 1;
                }
                let text = std::str::from_utf8(&self.bytes[start..self.at]).expect("ascii");
                match text.parse::<f64>() {
                    Ok(_) => Ok(Value::Number(text.to_owned())),
                    Err(_) => Err(self.fail("a number that is not one")),
                }
            }
            Some(_) => Err(self.fail("a character no value starts with")),
        }
    }

    fn hex4(&mut self) -> Result<u32, String> {
        let digits =
            self.bytes.get(self.at..self.at + 4).ok_or_else(|| self.fail("a short \\u"))?;
        let text = std::str::from_utf8(digits).map_err(|_| self.fail("a \\u that is not hex"))?;
        let n = u32::from_str_radix(text, 16).map_err(|_| self.fail("a \\u that is not hex"))?;
        self.at += 4;
        Ok(n)
    }

    fn string(&mut self) -> Result<String, String> {
        self.at += 1;
        let mut out: Vec<u8> = Vec::new();
        loop {
            let Some(b) = self.peek() else {
                return Err(self.fail("a string that never ends"));
            };
            self.at += 1;
            match b {
                b'"' => break,
                b'\\' => {
                    let Some(e) = self.peek() else {
                        return Err(self.fail("a string that ends in a backslash"));
                    };
                    self.at += 1;
                    let c = match e {
                        b'"' => '"',
                        b'\\' => '\\',
                        b'/' => '/',
                        b'b' => '\u{8}',
                        b'f' => '\u{c}',
                        b'n' => '\n',
                        b'r' => '\r',
                        b't' => '\t',
                        b'u' => {
                            let high = self.hex4()?;
                            let code = if (0xd800..0xdc00).contains(&high)
                                && self.bytes[self.at..].starts_with(b"\\u")
                            {
                                self.at += 2;
                                let low = self.hex4()?;
                                if !(0xdc00..0xe000).contains(&low) {
                                    return Err(self.fail("half a surrogate pair"));
                                }
                                0x10000 + ((high - 0xd800) << 10) + (low - 0xdc00)
                            } else {
                                high
                            };
                            char::from_u32(code).unwrap_or('\u{fffd}')
                        }
                        _ => return Err(self.fail("an escape JSON does not have")),
                    };
                    let mut buf = [0u8; 4];
                    out.extend_from_slice(c.encode_utf8(&mut buf).as_bytes());
                }
                _ => out.push(b),
            }
        }
        String::from_utf8(out).map_err(|_| self.fail("a string that is not UTF-8"))
    }
}

/// Splits a command line the way a POSIX shell would split it into words, which is how the
/// `command` form of a compile database entry is meant to be read.
///
/// Quotes and backslashes only, because a compile command has no expansions in it. Meson writes
/// the `-DVAL_CC="..."` defines of Postgres's `config_info.c` inside single quotes, and those are
/// the reason this is not a split on spaces.
#[must_use]
pub fn split_command(line: &str) -> Vec<String> {
    let mut words = Vec::new();
    let mut word = String::new();
    let mut started = false;
    let mut chars = line.chars();
    while let Some(c) = chars.next() {
        match c {
            ' ' | '\t' | '\n' => {
                if started {
                    words.push(std::mem::take(&mut word));
                    started = false;
                }
            }
            '\'' => {
                started = true;
                for c in chars.by_ref() {
                    if c == '\'' {
                        break;
                    }
                    word.push(c);
                }
            }
            '"' => {
                started = true;
                while let Some(c) = chars.next() {
                    match c {
                        '"' => break,
                        '\\' => match chars.next() {
                            Some(next @ ('"' | '\\' | '$' | '`')) => word.push(next),
                            Some('\n') => {}
                            Some(other) => {
                                word.push('\\');
                                word.push(other);
                            }
                            None => word.push('\\'),
                        },
                        other => word.push(other),
                    }
                }
            }
            '\\' => {
                started = true;
                match chars.next() {
                    Some('\n') | None => {}
                    Some(next) => word.push(next),
                }
            }
            other => {
                started = true;
                word.push(other);
            }
        }
    }
    if started {
        words.push(word);
    }
    words
}

/// The flags of one compile that say what the file means, with the ones that say what to do with
/// it taken out.
///
/// The pipeline check asks rucc for its intermediate forms on standard output, so the output file,
/// the `-c` and the dependency file flags would all be wrong on its command line. Diagnostic colour
/// goes too, since the output is read by this harness and written into a report rather than shown
/// on a terminal. Everything else stays: the include paths, the defines, the warnings and the
/// `-f` and `-m` flags are what the build compiled the file with.
#[must_use]
pub fn compile_flags(arguments: &[String], file: &str) -> Vec<String> {
    let mut kept = Vec::new();
    let mut rest = arguments.iter().skip(1);
    while let Some(arg) = rest.next() {
        match arg.as_str() {
            "-c" | "-MD" | "-MMD" | "-MP" => {}
            "-o" | "-MF" | "-MQ" | "-MT" => {
                rest.next();
            }
            a if a == file => {}
            a if a.starts_with("-fdiagnostics-color") => {}
            _ => kept.push(arg.clone()),
        }
    }
    kept
}

/// A path with its `.` and `..` components taken out without asking the file system, so that a
/// file meson names as `../postgres/src/port/x.c` from the build directory can be recognised as
/// being under the source directory it records.
#[must_use]
pub fn lexical(path: &Path) -> PathBuf {
    let mut out = PathBuf::new();
    for part in path.components() {
        match part {
            Component::CurDir => {}
            Component::ParentDir => {
                if !out.pop() {
                    out.push("..");
                }
            }
            other => out.push(other),
        }
    }
    out
}

/// The library or program a compile belongs to, read off the object's directory, which meson
/// names after the target with `.p` on the end.
fn target_of(output: &str) -> Option<String> {
    Path::new(output)
        .components()
        .filter_map(|c| c.as_os_str().to_str())
        .find_map(|c| c.strip_suffix(".p"))
        .map(str::to_owned)
}

/// One compile, as the database records it.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Entry {
    /// The directory the compile runs in.
    pub directory: PathBuf,
    /// The source file as the entry spells it, which is usually relative to `directory`.
    pub file: String,
    /// The object it writes, relative to `directory`.
    pub output: String,
    /// The compile's command line, compiler first.
    pub arguments: Vec<String>,
}

/// Reads a compile database.
///
/// # Errors
///
/// When the text is not JSON, or is not an array of entries each with a `directory`, a `file` and
/// either an `arguments` array or a `command` string.
pub fn entries(text: &str, whose: &str) -> Result<Vec<Entry>, Error> {
    let fail = |message: String| Error { message: format!("{whose}: {message}") };
    let Value::Array(items) = parse(text).map_err(fail)? else {
        return Err(fail("the database is not an array".to_owned()));
    };
    let mut out = Vec::new();
    for (at, item) in items.iter().enumerate() {
        let field = |key: &str| item.get(key).and_then(Value::as_str);
        let (Some(directory), Some(file)) = (field("directory"), field("file")) else {
            return Err(fail(format!("entry {at} has no `directory` or no `file`")));
        };
        let arguments = match (item.get("arguments"), field("command")) {
            (Some(Value::Array(words)), _) => {
                let words: Option<Vec<String>> =
                    words.iter().map(|w| w.as_str().map(str::to_owned)).collect();
                words.ok_or_else(|| {
                    fail(format!("entry {at} has an argument that is not a string"))
                })?
            }
            (_, Some(command)) => split_command(command),
            _ => return Err(fail(format!("entry {at} has neither `arguments` nor `command`"))),
        };
        out.push(Entry {
            directory: PathBuf::from(directory),
            file: file.to_owned(),
            output: field("output").unwrap_or_default().to_owned(),
            arguments,
        });
    }
    Ok(out)
}

/// What meson says about the build directory: where the source is, and which version of the
/// project it is a build of.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Info {
    /// The source directory the build was configured from.
    pub source: PathBuf,
    /// The project's version, as its `meson.build` declares it.
    pub version: String,
}

/// Reads `meson-info` in a build directory.
///
/// # Errors
///
/// When either file is missing or does not say what it should.
pub fn info(build: &Path) -> Result<Info, Error> {
    let read = |name: &str| -> Result<Value, Error> {
        let path = build.join("meson-info").join(name);
        let text = fs::read_to_string(&path)
            .map_err(|e| Error { message: format!("{}: {e}", path.display()) })?;
        parse(&text).map_err(|e| Error { message: format!("{}: {e}", path.display()) })
    };
    let dirs = read("meson-info.json")?;
    let source =
        dirs.get("directories").and_then(|d| d.get("source")).and_then(Value::as_str).ok_or_else(
            || Error {
                message: format!("{}: meson-info.json names no source directory", build.display()),
            },
        )?;
    let project = read("intro-projectinfo.json")?;
    let version = project.get("version").and_then(Value::as_str).ok_or_else(|| Error {
        message: format!("{}: intro-projectinfo.json names no version", build.display()),
    })?;
    Ok(Info { source: PathBuf::from(source), version: version.to_owned() })
}

/// Every compile in the build directory's database, as cases of one unit.
///
/// A case is named after its file relative to the source directory, or to the build directory for
/// a file the build generated, so the names are the same on every machine whatever the two
/// directories are called. A file compiled more than once, which Postgres does for each of the
/// libraries `src/port` and `src/common` go into, gets the target on the end after an `@`, since
/// those compiles have different defines and are different cases.
///
/// # Errors
///
/// When the database or `meson-info` cannot be read, or the build is of a version other than the
/// one the manifest says.
pub fn cases(build: &Path, version: &str, unit: &Unit, out: &mut Found) -> Result<(), Error> {
    let info = info(build)?;
    if info.version != version {
        return Err(Error {
            message: format!(
                "{} is a build of version {}, and the manifest is about {version}",
                build.display(),
                info.version
            ),
        });
    }
    let path = build.join(DATABASE);
    let text = fs::read_to_string(&path)
        .map_err(|e| Error { message: format!("{}: {e}", path.display()) })?;
    let entries = entries(&text, &path.display().to_string())?;
    let source = lexical(&info.source);
    let build_dir = lexical(build);
    let named: Vec<String> = entries
        .iter()
        .map(|entry| {
            let full = lexical(&entry.directory.join(&entry.file));
            let short = full
                .strip_prefix(&source)
                .or_else(|_| full.strip_prefix(&build_dir))
                .unwrap_or(&full);
            short.to_string_lossy().replace('\\', "/")
        })
        .collect();
    let mut times: HashMap<&str, usize> = HashMap::new();
    for name in &named {
        *times.entry(name.as_str()).or_default() += 1;
    }
    let mut taken: HashMap<String, usize> = HashMap::new();
    for (entry, name) in entries.iter().zip(&named) {
        let mut name = name.clone();
        if times[name.as_str()] > 1 {
            if let Some(target) = target_of(&entry.output) {
                name = format!("{name}@{target}");
            }
        }
        // Two compiles of one file into one target would be a build that makes the same object
        // twice. Numbered rather than refused, so a database this does not expect still runs.
        let seen = taken.entry(name.clone()).or_default();
        *seen += 1;
        if *seen > 1 {
            name = format!("{name}#{seen}");
        }
        if unit.skip.iter().any(|s| name == *s || name.starts_with(&format!("{s}/"))) {
            out.never.push(format!("{}/{name}", unit.name));
            continue;
        }
        let mut flags = compile_flags(&entry.arguments, &entry.file);
        flags.extend(unit.flags.iter().cloned());
        out.cases.push(Case {
            unit: unit.name.clone(),
            name: format!("{}/{name}", unit.name),
            file: entry.directory.join(&entry.file),
            dir: entry.directory.clone(),
            flags,
        });
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::corpus::UnitKind;

    #[test]
    fn json_is_read_whole_with_its_escapes_undone() {
        let v = parse(r#" {"a": [1, -2.5e3, true, false, null], "b": "x\"y\\zé😀\n"} "#).unwrap();
        assert_eq!(v.get("b").and_then(Value::as_str), Some("x\"y\\z\u{e9}\u{1f600}\n"));
        let Some(Value::Array(a)) = v.get("a") else { panic!("not an array") };
        assert_eq!(a.len(), 5);
        assert_eq!(a[1], Value::Number("-2.5e3".to_owned()));
        assert_eq!(a[4], Value::Null);
    }

    #[test]
    fn text_that_is_not_json_is_refused_with_where_it_stopped() {
        for bad in ["", "[1,]", "{\"a\" 1}", "\"open", "[1] 2", "tru", "{1: 2}"] {
            assert!(parse(bad).is_err(), "{bad} was read");
        }
        let deep = "[".repeat(DEPTH + 2);
        assert!(parse(&deep).unwrap_err().contains("deep"));
    }

    #[test]
    fn a_command_is_split_the_way_a_shell_splits_it() {
        let words = split_command(r#"cc -Ia  '-DVAL="x y"' -DQ=\"z\" "a b\"c" -c f.c"#);
        assert_eq!(words, ["cc", "-Ia", "-DVAL=\"x y\"", "-DQ=\"z\"", "a b\"c", "-c", "f.c"]);
        assert_eq!(split_command("  ''  x"), ["", "x"]);
    }

    #[test]
    fn the_flags_that_say_where_output_goes_are_taken_out_and_the_rest_kept() {
        let args: Vec<String> = [
            "gcc",
            "-Isrc/include",
            "-fdiagnostics-color=always",
            "-DX",
            "-O2",
            "-MD",
            "-MQ",
            "a.o",
            "-MF",
            "a.o.d",
            "-o",
            "a.o",
            "-c",
            "../src/a.c",
        ]
        .iter()
        .map(|s| (*s).to_owned())
        .collect();
        assert_eq!(compile_flags(&args, "../src/a.c"), ["-Isrc/include", "-DX", "-O2"]);
    }

    #[test]
    fn dots_are_taken_out_of_a_path_without_the_file_system() {
        assert_eq!(lexical(Path::new("/b/build/../src/./x.c")), PathBuf::from("/b/src/x.c"));
        assert_eq!(lexical(Path::new("../x.c")), PathBuf::from("../x.c"));
    }

    fn unit(skip: &[&str]) -> Unit {
        Unit {
            name: "meson".to_owned(),
            kind: UnitKind::CompileCommands,
            files: Vec::new(),
            dir: None,
            skip: skip.iter().map(|s| (*s).to_owned()).collect(),
            flags: vec!["-DEXTRA".to_owned()],
            link: Vec::new(),
            libs: Vec::new(),
            seconds: None,
            megabytes: None,
        }
    }

    fn build_dir(name: &str) -> PathBuf {
        let root =
            std::env::temp_dir().join(format!("rucc-compat-meson-{name}-{}", std::process::id()));
        let _ = fs::remove_dir_all(&root);
        let build = root.join("build");
        fs::create_dir_all(build.join("meson-info")).unwrap();
        let source = root.join("src").display().to_string().replace('\\', "/");
        let dir = build.display().to_string().replace('\\', "/");
        fs::write(
            build.join("meson-info/meson-info.json"),
            format!("{{\"directories\": {{\"source\": \"{source}\", \"build\": \"{dir}\"}}}}"),
        )
        .unwrap();
        fs::write(build.join("meson-info/intro-projectinfo.json"), "{\"version\": \"18.6\"}")
            .unwrap();
        let entry = |file: &str, target: &str, extra: &str| {
            format!(
                "{{\"directory\": \"{dir}\", \"command\": \"cc -I{target}.p {extra} -o {target}.p/x.o -c {file}\", \"file\": \"{file}\", \"output\": \"{target}.p/x.o\"}}"
            )
        };
        let db = format!(
            "[{}, {}, {}, {}]",
            entry("../src/port/a.c", "libport_srv.a", "-DSRV"),
            entry("../src/port/a.c", "libport.a", "-DFRONTEND"),
            entry("../src/main.c", "postgres", ""),
            entry("gen/gram.c", "postgres", ""),
        );
        fs::write(build.join(DATABASE), db).unwrap();
        build
    }

    #[test]
    fn each_compile_is_a_case_named_from_the_source_or_the_build_directory() {
        let build = build_dir("cases");
        let mut found = Found::default();
        cases(&build, "18.6", &unit(&["main.c"]), &mut found).unwrap();
        let names: Vec<&str> = found.cases.iter().map(|c| c.name.as_str()).collect();
        assert_eq!(
            names,
            ["meson/port/a.c@libport_srv.a", "meson/port/a.c@libport.a", "meson/gen/gram.c"]
        );
        assert_eq!(found.never, ["meson/main.c"]);
        let first = &found.cases[0];
        assert_eq!(first.dir, build);
        assert_eq!(first.file, build.join("../src/port/a.c"));
        assert_eq!(first.flags, ["-Ilibport_srv.a.p", "-DSRV", "-DEXTRA"]);
        assert_eq!(found.cases[1].flags, ["-Ilibport.a.p", "-DFRONTEND", "-DEXTRA"]);
        let _ = fs::remove_dir_all(build.parent().unwrap());
    }

    #[test]
    fn a_build_of_another_version_is_refused() {
        let build = build_dir("version");
        let e = cases(&build, "17.2", &unit(&[]), &mut Found::default()).unwrap_err();
        assert!(e.message.contains("18.6") && e.message.contains("17.2"), "{}", e.message);
        let _ = fs::remove_dir_all(build.parent().unwrap());
    }
}
